n = float(input('Digite uma distância em metros: '))
print(f'A medida de {n} corresponde a')
print(f'{n/1000}km')
print(f'{n/100}hm')
print(f'{n/10}dam')
print(f'{n*10}dm')
print(f'{n*100}cm')
print(f'{n*1000}mm')